//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkin_dichvu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public checkin_dichvu()
        {
            this.dv_trunggian = new HashSet<dv_trunggian>();
        }
    
        public int id { get; set; }
        public int idcheckin { get; set; }
        public int iddv { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual checkin checkin { get; set; }
        public virtual dichvu dichvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dv_trunggian> dv_trunggian { get; set; }
    }
}
