//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsdattruoc
    {
        public int id { get; set; }
        public Nullable<int> idnv { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<int> idphong { get; set; }
        public Nullable<System.DateTime> ngayden { get; set; }
        public Nullable<System.DateTime> ngaydi { get; set; }
        public Nullable<bool> ttphong { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
    
        public virtual phong phong { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
