//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon_dichvu
    {
        public int idhoadon { get; set; }
        public string Tên_nhân_viên { get; set; }
        public string Tên_khách_hàng { get; set; }
        public string Tên_dịch_vụ { get; set; }
        public Nullable<int> Số_lượng { get; set; }
        public Nullable<decimal> Giá_tiền { get; set; }
        public System.DateTime Ngày_tạo { get; set; }
    }
}
