//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DAQLKS : DbContext
    {
        public DAQLKS()
            : base("name=DAQLKS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<checkin> checkins { get; set; }
        public virtual DbSet<checkin_dichvu> checkin_dichvu { get; set; }
        public virtual DbSet<checkin_phong> checkin_phong { get; set; }
        public virtual DbSet<checkout> checkouts { get; set; }
        public virtual DbSet<dichvu> dichvus { get; set; }
        public virtual DbSet<dv_trunggian> dv_trunggian { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<khuvuc> khuvucs { get; set; }
        public virtual DbSet<loaiphong> loaiphongs { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phong> phongs { get; set; }
        public virtual DbSet<phong_trunggian> phong_trunggian { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<tempkhachhang> tempkhachhangs { get; set; }
        public virtual DbSet<trangthaiphong> trangthaiphongs { get; set; }
        public virtual DbSet<vaitro> vaitroes { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<hoadon_dichvu> hoadon_dichvu { get; set; }
        public virtual DbSet<hoadon_phong> hoadon_phong { get; set; }
    
        public virtual int xoanhanvien(Nullable<int> idnhanvien)
        {
            var idnhanvienParameter = idnhanvien.HasValue ?
                new ObjectParameter("idnhanvien", idnhanvien) :
                new ObjectParameter("idnhanvien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoanhanvien", idnhanvienParameter);
        }
    }
}
