//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class phong_trunggian
    {
        public int idp { get; set; }
        public int idhd { get; set; }
        public string mota { get; set; }
    
        public virtual checkin_phong checkin_phong { get; set; }
        public virtual hoadon hoadon { get; set; }
    }
}
