//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phong()
        {
            this.checkin_phong = new HashSet<checkin_phong>();
            this.dsdattruocs = new HashSet<dsdattruoc>();
        }
    
        public int idphong { get; set; }
        public int loaiphong { get; set; }
        public int khuvuc { get; set; }
        public string tenphong { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> tt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkin_phong> checkin_phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dsdattruoc> dsdattruocs { get; set; }
        public virtual khuvuc khuvuc1 { get; set; }
        public virtual loaiphong loaiphong1 { get; set; }
    }
}
