//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempkhachhang
    {
        public int idkh { get; set; }
        public int idcheckin { get; set; }
        public Nullable<decimal> tienkhachtra { get; set; }
    
        public virtual checkin checkin { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
