//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dsdattruoc_chitiet
    {
        public int idphong { get; set; }
        public string tenphong { get; set; }
        public string loaiphong { get; set; }
        public string mota { get; set; }
        public decimal giaphong { get; set; }
        public string tenkhuvuc { get; set; }
        public string ten_nhanvien { get; set; }
        public string ten_khachhang { get; set; }
        public Nullable<System.DateTime> ngayden { get; set; }
        public Nullable<System.DateTime> ngaydi { get; set; }
        public Nullable<bool> ttphong { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
    }
}
