//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewhoadon
    {
        public int idhoadon { get; set; }
        public string tenphong { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string ten { get; set; }
        public System.DateTime ngaycheckin { get; set; }
        public System.DateTime ngaycheckout { get; set; }
        public Nullable<decimal> tienkhachtra { get; set; }
        public int idcheckin { get; set; }
        public int idphong { get; set; }
        public string tennhanvien { get; set; }
    }
}
