//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trangthai_phong_hientai
    {
        public int idphong { get; set; }
        public string tenphong { get; set; }
        public string loaiphong { get; set; }
        public decimal giaphong { get; set; }
        public string tenkhuvuc { get; set; }
        public int trangthai { get; set; }
        public string trangthai_text { get; set; }
    }
}
