//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Quanly.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DuAn1 : DbContext
    {
        public DuAn1()
            : base("name=DuAn1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<checkin> checkins { get; set; }
        public virtual DbSet<checkin_dichvu> checkin_dichvu { get; set; }
        public virtual DbSet<checkin_phong> checkin_phong { get; set; }
        public virtual DbSet<checkout> checkouts { get; set; }
        public virtual DbSet<dichvu> dichvus { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<hoadonchitiet> hoadonchitiets { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaiphong> loaiphongs { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phong> phongs { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<trangthaiphong> trangthaiphongs { get; set; }
        public virtual DbSet<vaitro> vaitroes { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
    }
}
